# Generated by Django 2.1.4 on 2018-12-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubtime', models.DateField(verbose_name='日期')),
                ('mood', models.FloatField(verbose_name='心情')),
                ('mood_keywords', models.CharField(default='', max_length=255, verbose_name='心情关键词')),
                ('consume', models.FloatField(default=0.0, verbose_name='消费额(元)')),
                ('consume_keywords', models.CharField(default='', max_length=255, verbose_name='消费关键词')),
                ('time_keywords', models.CharField(default='', max_length=255, verbose_name='时间分布(时)')),
                ('consume_log', models.TextField(default='', verbose_name='消费日志')),
                ('time_log', models.TextField(default='', verbose_name='时间日志')),
                ('event_log', models.TextField(default='', verbose_name='事件日志')),
            ],
            options={
                'verbose_name_plural': '数据',
            },
        ),
    ]
