# Generated by Django 2.1.4 on 2018-12-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='keywords',
            field=models.CharField(default='', max_length=255, verbose_name='关键词'),
        ),
    ]
